# BCG X:
![BCG-X](BCG_X.png)
    
  
    BCG X is transforming businesses using data science to help companies generate competitive advantage. To do this, we typically follow a 5-step methodology:

    [1] Business understanding & problem framing
    [2] Exploratory data analysis & data cleaning
    [3] Feature engineering
    [4] Modeling and evaluation
    [5] Insights & Recommendations

#  Step 1:-Lets get started from importing Libraries...

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Shows plots in jupyter notebook
%matplotlib inline
# Set plot style
sns.set(color_codes=True)

## Loading data with Pandas

We need to load `client_data.csv` and `price_data.csv` into individual dataframes so that we can work with them in Python. For this notebook and all further notebooks, it will be assumed that the CSV files will the placed in the same file location as the notebook. If they are not, please adjust the directory within the `read_csv` method accordingly.

In [6]:
client_data = pd.read_csv("client_data.csv")

In [7]:
price_data = pd.read_csv("price_data.csv")

In [ ]:
client_data.head(20) # to see the type of formate of values and check whether the data has been loaded correctlly...

,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,...,has_gas,imp_cons,margin_gross_pow_ele,margin_net_pow_ele,nb_prod_act,net_margin,num_years_antig,origin_up,pow_max,churn
0,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,...,t,0.00,25.44,25.44,2,678.99,3,lxidpiddsbxsbosboudacockeimpuepw,43.648,1
1,d29c2c54acc38ff3c0614d0a653813dd,MISSING,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,...,f,0.00,16.38,16.38,1,18.89,6,kamkkxfxxuwbdslkwifmmcsiusiuosws,13.800,0
2,764c75f661154dac3a6c254cd082ea7d,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,...,f,0.00,28.60,28.60,1,6.60,6,kamkkxfxxuwbdslkwifmmcsiusiuosws,13.856,0
3,bba03439a292a1e166f80264c16191cb,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,240.04,...,f,0.00,30.22,30.22,1,25.46,6,kamkkxfxxuwbdslkwifmmcsiusiuosws,13.200,0
4,149d57cf92fc41cf94415803a877cb4b,MISSING,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,445.75,...,f,52.32,44.91,44.91,1,47.98,6,kamkkxfxxuwbdslkwifmmcsiusiuosws,19.800,0
5,1aa498825382410b098937d65c4ec26d,usilxuppasemubllopkaafesmlibmsdf,8302,0,1998,2011-12-09,2016-12-09,2015-11-01,2015-12-10,796.94,...,f,181.21,33.12,33.12,1,118.89,4,lxidpiddsbxsbosboudacockeimpuepw,13.200,1
6,7ab4bf4878d8f7661dfc20e9b8e18011,foosdfpfkusacimwkcsosbicdxkicaua,45097,0,0,2011-12-02,2016-12-02,2011-12-02,2015-12-03,8069.28,...,f,0.00,4.04,4.04,1,346.63,4,lxidpiddsbxsbosboudacockeimpuepw,15.000,1
7,01495c955be7ec5e7f3203406785aae0,foosdfpfkusacimwkcsosbicdxkicaua,29552,0,1260,2010-04-21,2016-04-21,2010-04-21,2015-04-22,864.73,...,f,70.63,53.92,53.92,1,100.09,6,lxidpiddsbxsbosboudacockeimpuepw,26.400,0
8,f53a254b1115634330c12c7fdbf7958a,usilxuppasemubllopkaafesmlibmsdf,2962,0,0,2011-09-23,2016-09-23,2011-09-23,2015-09-25,444.38,...,f,0.00,12.82,12.82,1,42.59,4,kamkkxfxxuwbdslkwifmmcsiusiuosws,13.200,0
9,10c1b2f97a2d2a6f10299dc213d1a370,lmkebamcaaclubfxadlmueccxoimlema,26064,0,2188,2010-05-04,2016-05-04,2015-04-29,2015-05-05,2738.10,...,f,219.59,33.42,33.42,1,329.60,6,lxidpiddsbxsbosboudacockeimpuepw,31.500,0
10,d5e512dbc8118a830a7b8c7f61d89992,usilxuppasemubllopkaafesmlibmsdf,10831,0,3112,2011-07-11,2016-07-11,2011-07-11,2015-07-12,1204.58,...,f,349.48,14.52,14.52,1,108.50,5,kamkkxfxxuwbdslkwifmmcsiusiuosws,11.500,0
11,6ee77a019251bcc304c88167e0dfcb4c,foosdfpfkusacimwkcsosbicdxkicaua,4442,0,2489,2009-11-26,2016-11-26,2009-11-26,2015-11-27,561.96,...,f,308.41,21.09,21.09,1,18.41,6,kamkkxfxxuwbdslkwifmmcsiusiuosws,10.392,0
12,2c05848e1a577dd041ea6804bbf5bbf5,foosdfpfkusacimwkcsosbicdxkicaua,46121,1542867,5280,2011-09-01,2016-10-30,2013-10-30,2015-11-01,4502.43,...,t,523.68,5.52,5.52,2,533.46,4,lxidpiddsbxsbosboudacockeimpuepw,16.500,0
13,21860c2ff2d5df75503b230ce629c253,foosdfpfkusacimwkcsosbicdxkicaua,7726,0,0,2013-01-22,2017-01-22,2015-11-18,2016-01-24,914.10,...,f,0.00,33.12,33.12,1,89.02,3,ldkssxwpmemidmecebumciepifcamkci,13.200,0
14,c5037389dd8be351d3c40f2973da2391,MISSING,9707,0,0,2010-12-01,2016-12-01,2010-12-01,2015-12-02,1028.52,...,f,0.00,15.78,15.78,1,111.59,5,kamkkxfxxuwbdslkwifmmcsiusiuosws,13.856,0
15,e4773b60d2e68aac94795782abfc006b,lmkebamcaaclubfxadlmueccxoimlema,47019,0,3161,2012-04-20,2016-04-20,2012-04-20,2015-04-21,1687.29,...,f,158.53,19.28,19.28,1,130.14,4,ldkssxwpmemidmecebumciepifcamkci,10.392,0
16,bd14bbac3aca710ee5288fcd8511d4bb,MISSING,786536,80583,85883,2010-02-15,2016-02-15,2010-02-15,2015-02-16,13517.50,...,t,2585.38,25.68,25.68,2,1087.76,6,lxidpiddsbxsbosboudacockeimpuepw,11.400,0
17,4e4a34a6d91ff25d0fdf68733907ad44,foosdfpfkusacimwkcsosbicdxkicaua,30776,0,0,2011-08-01,2016-07-25,2014-07-25,2015-07-27,3045.16,...,f,0.00,19.29,19.29,1,335.78,5,MISSING,25.000,0
18,f2b93783adecf0d0d8d60ab547bda3de,MISSING,24838,0,2877,2011-05-27,2016-05-27,2011-05-27,2015-05-31,1088.35,...,f,79.36,21.57,21.57,1,117.44,5,ldkssxwpmemidmecebumciepifcamkci,15.001,0
19,47e976c5d7f1ee1fee6d60ca39fd0218,foosdfpfkusacimwkcsosbicdxkicaua,15411,0,0,2012-05-28,2016-05-28,2012-05-28,2015-05-31,194.42,...,f,0.00,23.97,23.97,1,19.07,4,lxidpiddsbxsbosboudacockeimpuepw,13.000,0

In [27]:
# You can view the first 3 rows of a dataframe using the `head` method. Similarly, if you wanted to see the last 3, you can use `tail(3)`

In [ ]:
price_data.head(20) # to see the type of formate of values and check whether the data has been loaded correctlly...

,id,price_date,price_off_peak_var,price_peak_var,price_mid_peak_var,price_off_peak_fix,price_peak_fix,price_mid_peak_fix
0,038af19179925da21a25619c5a24b745,2015-01-01,0.151367,0.000000,0.000000,44.266931,0.000000,0.000000
1,038af19179925da21a25619c5a24b745,2015-02-01,0.151367,0.000000,0.000000,44.266931,0.000000,0.000000
2,038af19179925da21a25619c5a24b745,2015-03-01,0.151367,0.000000,0.000000,44.266931,0.000000,0.000000
3,038af19179925da21a25619c5a24b745,2015-04-01,0.149626,0.000000,0.000000,44.266931,0.000000,0.000000
4,038af19179925da21a25619c5a24b745,2015-05-01,0.149626,0.000000,0.000000,44.266931,0.000000,0.000000
5,038af19179925da21a25619c5a24b745,2015-06-01,0.149626,0.000000,0.000000,44.266930,0.000000,0.000000
6,038af19179925da21a25619c5a24b745,2015-07-01,0.150321,0.000000,0.000000,44.444710,0.000000,0.000000
7,038af19179925da21a25619c5a24b745,2015-08-01,0.145859,0.000000,0.000000,44.444710,0.000000,0.000000
8,038af19179925da21a25619c5a24b745,2015-09-01,0.145859,0.000000,0.000000,44.444710,0.000000,0.000000
9,038af19179925da21a25619c5a24b745,2015-10-01,0.145859,0.000000,0.000000,44.444710,0.000000,0.000000
10,038af19179925da21a25619c5a24b745,2015-11-01,0.145859,0.000000,0.000000,44.444710,0.000000,0.000000
11,038af19179925da21a25619c5a24b745,2015-12-01,0.145859,0.000000,0.000000,44.444710,0.000000,0.000000
12,31f2ce549924679a3cbb2d128ae9ea43,2015-01-01,0.125976,0.103395,0.071536,40.565969,24.339581,16.226389
13,31f2ce549924679a3cbb2d128ae9ea43,2015-02-01,0.125976,0.103395,0.071536,40.565969,24.339581,16.226389
14,31f2ce549924679a3cbb2d128ae9ea43,2015-03-01,0.125976,0.103395,0.071536,40.565969,24.339581,16.226389
15,31f2ce549924679a3cbb2d128ae9ea43,2015-04-01,0.125976,0.103395,0.071536,40.565969,24.339581,16.226389
16,31f2ce549924679a3cbb2d128ae9ea43,2015-05-01,0.124815,0.102234,0.070375,40.565969,24.339581,16.226389
17,31f2ce549924679a3cbb2d128ae9ea43,2015-06-01,0.126916,0.105240,0.075150,40.728885,24.437330,16.291555
18,31f2ce549924679a3cbb2d128ae9ea43,2015-07-01,0.126916,0.105240,0.075150,40.728885,24.437330,16.291555
19,31f2ce549924679a3cbb2d128ae9ea43,2015-08-01,0.118755,0.101071,0.075096,40.728885,24.437330,16.291555

#  Step 2:-Exploratory Data Analysis Starter

In [25]:
client_data.shape #to understand the dimension of the datasets,it tells us how many rows and columns have,which gives me an initial understanding of yhe dataset sizes

(14606, 26)

In [26]:
price_data.shape #to understand the dimension of the datasets,it tells us how many rows and columns have,which gives me an initial understanding of yhe dataset sizes

(193002, 8)

In [15]:
client_data.describe()

,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,forecast_cons_year,forecast_discount_energy,forecast_meter_rent_12m,forecast_price_energy_off_peak,forecast_price_energy_peak,forecast_price_pow_off_peak,imp_cons,margin_gross_pow_ele,margin_net_pow_ele,nb_prod_act,net_margin,num_years_antig,pow_max,churn
count,1.460600e+04,1.460600e+04,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000
mean,1.592203e+05,2.809238e+04,16090.269752,1868.614880,1399.762906,0.966726,63.086871,0.137283,0.050491,43.130056,152.786896,24.565121,24.562517,1.292346,189.264522,4.997809,18.135136,0.097152
std,5.734653e+05,1.629731e+05,64364.196422,2387.571531,3247.786255,5.108289,66.165783,0.024623,0.049037,4.485988,341.369366,20.231172,20.230280,0.709774,311.798130,1.611749,13.534743,0.296175
min,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,3.300000,0.000000
25%,5.674750e+03,0.000000e+00,0.000000,494.995000,0.000000,0.000000,16.180000,0.116340,0.000000,40.606701,0.000000,14.280000,14.280000,1.000000,50.712500,4.000000,12.500000,0.000000
50%,1.411550e+04,0.000000e+00,792.500000,1112.875000,314.000000,0.000000,18.795000,0.143166,0.084138,44.311378,37.395000,21.640000,21.640000,1.000000,112.530000,5.000000,13.856000,0.000000
75%,4.076375e+04,0.000000e+00,3383.000000,2401.790000,1745.750000,0.000000,131.030000,0.146348,0.098837,44.311378,193.980000,29.880000,29.880000,1.000000,243.097500,6.000000,19.172500,0.000000
max,6.207104e+06,4.154590e+06,771203.000000,82902.830000,175375.000000,30.000000,599.310000,0.273963,0.195975,59.266378,15042.790000,374.640000,374.640000,32.000000,24570.650000,13.000000,320.000000,1.000000

In [16]:
price_data.describe()

,price_off_peak_var,price_peak_var,price_mid_peak_var,price_off_peak_fix,price_peak_fix,price_mid_peak_fix
count,193002.000000,193002.000000,193002.000000,193002.000000,193002.000000,193002.000000
mean,0.141027,0.054630,0.030496,43.334477,10.622875,6.409984
std,0.025032,0.049924,0.036298,5.410297,12.841895,7.773592
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.125976,0.000000,0.000000,40.728885,0.000000,0.000000
50%,0.146033,0.085483,0.000000,44.266930,0.000000,0.000000
75%,0.151635,0.101673,0.072558,44.444710,24.339581,16.226389
max,0.280700,0.229788,0.114102,59.444710,36.490692,17.458221

In [20]:
client_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 14606 entries, 0 to 14605
Data columns (total 26 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              14606 non-null  str
 1   channel_sales                   14606 non-null  str
 2   cons_12m                        14606 non-null  int64
 3   cons_gas_12m                    14606 non-null  int64
 4   cons_last_month                 14606 non-null  int64
 5   date_activ                      14606 non-null  str
 6   date_end                        14606 non-null  str
 7   date_modif_prod                 14606 non-null  str
 8   date_renewal                    14606 non-null  str
 9   forecast_cons_12m               14606 non-null  float64
 10  forecast_cons_year              14606 non-null  int64
 11  forecast_discount_energy        14606 non-null  float64
 12  forecast_meter_rent_12m         14606 non-null  float64
 13  forecast_price_energy_off_peak  14606 non-null  float64
 14  forecast_price_energy_peak      14606 non-null  float64
 15  forecast_price_pow_off_peak     14606 non-null  float64
 16  has_gas                         14606 non-null  str
 17  imp_cons                        14606 non-null  float64
 18  margin_gross_pow_ele            14606 non-null  float64
 19  margin_net_pow_ele              14606 non-null  float64
 20  nb_prod_act                     14606 non-null  int64
 21  net_margin                      14606 non-null  float64
 22  num_years_antig                 14606 non-null  int64
 23  origin_up                       14606 non-null  str
 24  pow_max                         14606 non-null  float64
 25  churn                           14606 non-null  int64
dtypes: float64(11), int64(7), str(8)
memory usage: 4.7 MB

In [21]:
price_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 193002 entries, 0 to 193001
Data columns (total 8 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  193002 non-null  str
 1   price_date          193002 non-null  str
 2   price_off_peak_var  193002 non-null  float64
 3   price_peak_var      193002 non-null  float64
 4   price_mid_peak_var  193002 non-null  float64
 5   price_off_peak_fix  193002 non-null  float64
 6   price_peak_fix      193002 non-null  float64
 7   price_mid_peak_fix  193002 non-null  float64
dtypes: float64(6), str(2)
memory usage: 19.5 MB